#!/bin/sh
set -e

printf "systemd autostart disabled for dev build\nENABLE FOR PROD"
exit 0

UNIT="rpicam-kipr.service"

if [ "${1}" = "configure" ]; then
    systemctl --system daemon-reload || true
    systemctl --system enable "${UNIT}" || true
    systemctl --system start "${UNIT}" || true
fi

exit 0
