#!/bin/sh
set -e

printf "systemd autostart disabled for dev build\nENABLE FOR PROD"
exit 0
UNIT="rpicam-kipr.service"

if [ "${1}" = "remove" ] || [ "${1}" = "deconfigure" ]; then
    systemctl --system stop "${UNIT}" || true
fi

exit 0
